### ISSUE TITLE
正版试用期已过，还有办法解救吗？

### ISSUE THREAD

**Issue by Charliego93** [MikeWang000000/PD-Runner-Revived#1]
之前电脑安装过正版的，现在已经过了试用期了，之后才使用PD Runner，提示没有试用，多次卸载重新安装PD15， 16，17。仍然无法重新试用，这种情况是不是就无缘了。

**Comment by MikeWang000000** [comment]
先将本地时间调至试用周期内，启动虚拟机后，再将日期修改回当前时间。

**Comment by Charliego93** [comment]
问题是在首次下载PD Runner之后无法使用，因为已经过了试用期，之后将之前试用过的版本卸载重新安装了多次，新安装的现在无法激活试用了，也可以通过上述方式解决吗？

**Comment by pluto-ctrl** [comment]
> 

先卸载干净，改一下系统时间，再穿个账号重新申请试用就可以了。我也是这个问题

**Comment by Charliego93** [comment]
> > 
> 
> 
> 
> 先卸载干净，改一下系统时间，再穿个账号重新申请试用就可以了。我也是这个问题

上次卸载干净后重新创建了一个帐号还是不能激活试用，另外问一下系统时间修改到什么时间？第一次激活试用的时间段内？你的已经成功了吗？多谢。

**Comment by pluto-ctrl** [comment]
> 

我就是设置回第一次试用前的时间，先设置后再用另一个账户申请试用，重点：要卸载干净，可以用cleanmymac这个app。

**Comment by pluto-ctrl** [comment]
> > > 
> > 
> > 
> > 先卸载干净，改一下系统时间，再穿个账号重新申请试用就可以了。我也是这个问题
> 
> 上次卸载干净后重新创建了一个帐号还是不能激活试用，另外问一下系统时间修改到什么时间？第一次激活试用的时间段内？你的已经成功了吗？多谢。

我就是设置回第一次试用前的时间，先设置后再用另一个账户申请试用，重点：要卸载干净，可以用cleanmymac这个app。
