### ISSUE TITLE
大佬的开发者账号是不是又过期了？

### ISSUE THREAD

**Issue by CarterLi** [MikeWang000000/PD-Runner-Revived#10]
“PD Runner”将对您的电脑造成伤害。 您应该将它移到废纸篓。

**Comment by L1xiaolong** [comment]
> 

遇到了同样的问题，请问您找到解决办法了吗？

**Comment by land007** [comment]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/574543/183798715-dab6e5ba-35fe-43d5-9b03-c3de81c93177.png">

**Comment by land007** [comment]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/574543/183799695-e1b4a8a1-feb8-452a-92d9-08dd5a4b120e.png">

**Comment by L1xiaolong** [comment]
> <img alt="image" width="260" src="https://user-images.githubusercontent.com/574543/183799695-e1b4a8a1-feb8-452a-92d9-08dd5a4b120e.png">



> <img alt="image" width="260" src="https://user-images.githubusercontent.com/574543/183799695-e1b4a8a1-feb8-452a-92d9-08dd5a4b120e.png">



> <img alt="image" width="260" src="https://user-images.githubusercontent.com/574543/183799695-e1b4a8a1-feb8-452a-92d9-08dd5a4b120e.png">



> <img alt="image" width="260" src="https://user-images.githubusercontent.com/574543/183799695-e1b4a8a1-feb8-452a-92d9-08dd5a4b120e.png">



> <img alt="image" width="260" src="https://user-images.githubusercontent.com/574543/183799695-e1b4a8a1-feb8-452a-92d9-08dd5a4b120e.png">



> <img alt="image" width="260" src="https://user-images.githubusercontent.com/574543/183799695-e1b4a8a1-feb8-452a-92d9-08dd5a4b120e.png">

勾选了“覆盖恶意软件保护”也是同样提示应用程序无法打开，版本0.3.6

**Comment by ccf-zeno** [comment]
我也一样，测试了0.3.6与0.3.7版本均遇到了楼上的情况

**Comment by CarterLi** [comment]
> > 
> 
> 遇到了同样的问题，请问您找到解决办法了吗？

解决不了啊。本来想把代码拉下来自己编译一下，发现github上的代码都是史前版本的代码

**Comment by haydensu** [comment]
“PD Runner”将对您的电脑造成伤害。 您应该将它移到废纸篓。

**Comment by coral-zone** [comment]
应用程序无法打开      有解决方法吗？

**Comment by haydensu** [comment]
应用程序“PD Runner”无法打开。 有大佬有解决办法吗

**Comment by suemor233** [comment]
可以去这里下载 0.3.8 版本 https://macapp.org.cn/app/pd-runner.html

**Comment by ClassmateShen** [comment]
请于https://macapp.org.cn/app/pd-runner.html 重新下载。
MacApp分享频道网站是全网唯一的pd runner官方发布站点

**Comment by EtoDemerzel0427** [comment]
使用了新版本，问题并没有解决。
<img width="453" alt="image" src="https://user-images.githubusercontent.com/32998901/186542891-d2bb8cfb-0a91-4ce8-b61c-2375333e9570.png">

**Comment by Hust-ChengP** [comment]
> 使用了新版本，问题并没有解决。 <img alt="image" width="453" src="https://user-images.githubusercontent.com/32998901/186542891-d2bb8cfb-0a91-4ce8-b61c-2375333e9570.png">

点Show in Folder 然后删除这个文件 再重装就可以了 @EtoDemerzel0427
