### ISSUE TITLE
0.38 fxck PD18时，不断自动中止

### ISSUE THREAD

**Issue by Travel2Here** [MikeWang000000/PD-Runner-Revived#16]
试用窗口弹出时（虽然能自动关闭），但整个虚拟机会被中止，很频繁。不知道是不是我一个人的问题。

**Comment by mentalfl0w** [comment]
是的，我也存在这种问题，这应该是PD18全新的防盗版机制。

**Comment by BenjaminX** [comment]
PD18 修改了机制，这个不好修改了。除非有源码

**Comment by xiaoker** [comment]
现在很无语了
想退回 PD17.1都不行了，在 PD18更新了 arm 的 win11,回到PD17就进不去系统
不知道怎么解决

**Comment by mooneee** [comment]
我也是，难道要不能用了吗

**Comment by tyIceStream** [comment]
将Win11更新到最新版本之后可以在PD17中运行。

**Comment by licherqi** [comment]
有没有解决方案

**Comment by 578066229** [comment]
一样，一直弹窗，还会自动停止

**Comment by AntonyYu2017** [comment]
只要修改时间退到过期之前是可以不弹窗的，但不能改回去，上网会影响联网校验时间

**Comment by erow** [comment]
所以要间隔地心跳修改时间？

**Comment by duanhjlt** [comment]
同样的问题，有解决方案了么

**Comment by dmzzzzhlj90** [comment]
一样的问题，不知道有解决方案不😭

**Comment by tyIceStream** [comment]
Code里面搜prl_disp_service，可以激活

**Comment by Travel2Here** [comment]
> Code里面搜prl_disp_service，可以激活

可否借一步说话？😂详细给大家说说
