### ISSUE TITLE
PD runner for parallel 18

### ISSUE THREAD

**Issue by trace7087** [MikeWang000000/PD-Runner-Revived#18]
I used the new patched pd runner 3.8 today but sadly I am still getting the windows suspended every 5mins so I don't believe the patch is working too well in regards to this trial page keep coming up 👎 

<img width="854" alt="Screenshot 2022-09-21 at 19 02 47" src="https://user-images.githubusercontent.com/83868440/191577968-d3bc61cc-c49e-4691-be41-67c0a0f853de.png">

**Comment by 840103818** [comment]
I followed the txt file and found this problem. You can try. txtURl: https://github.com/MikeWang000000/PD-Runner-Revived/releases/download/0.3.8.01/for_advanced_users.txt

**Comment by 840103818** [comment]
> I used the new patched pd runner 3.8 today but sadly I am still getting the windows suspended every 5mins so I don't believe the patch is working too well in regards to this trial page keep coming up 👎
> 
> <img alt="Screenshot 2022-09-21 at 19 02 47" width="854" src="https://user-images.githubusercontent.com/83868440/191577968-d3bc61cc-c49e-4691-be41-67c0a0f853de.png">

I followed the txt file and found this problem. You can try. txtURl: https://github.com/MikeWang000000/PD-Runner-Revived/releases/download/0.3.8.01/for_advanced_users.txt

**Comment by stephanie-007** [comment]
You can try [this](https://github.com/utsanjan/PD-Runner). At least for me its working without getting suspended.

**Comment by trace7087** [comment]
Thanks for the tex file, worked like a dream no more problems 😃 thanks 🙏
