### ISSUE TITLE
Content mismatch: Not compatible with macOS Ventura / 未兼容 macOS Ventura

### ISSUE THREAD

**Issue by dorameonsu** [MikeWang000000/PD-Runner-Revived#19]
![IMAGE 2022-10-03 19:21:17](https://user-images.githubusercontent.com/85793026/193565050-046872db-7a9e-4c2c-9da0-fcbab8e34bbd.jpg)

**Comment by MikeWang000000** [comment]
Hello, I need more detailed information to check this issue.

Could you tell me which version of PD and macOS you are using?
MacBook / iMac model, System language, Apple Silicon or Intel?

**Comment by nonplaybox** [comment]
> Hello, I need more detailed information to check this issue.
> 
> Could you tell me which version of PD and macOS you are using? MacBook / iMac model, System language, Apple Silicon or Intel?

Hi, my macOS version is Ventura 13.0, and PD version is 18.0.2.
MacBook model : MacBook air m1 (Apple Silicon).
System language : English

**Comment by MikeWang000000** [comment]
Sorry PD Patcher is untested under macOS Ventura currently, I'm still in Monterey.
The new macOS may have added new security policies that cause PD Patcher to fail :(

**Comment by MikeWang000000** [comment]
I just found out that macOS Ventura added a new permission “App Management”.
In **System Preferences** > **Privacy & Security** > **App Management**, click "+" button, add "PDPatcher.app".
Then try it again? Also don't forget to give it "Full Disk Access" :)

**Comment by nonplaybox** [comment]
> I just found out that macOS Ventura added a new permission “App Management”.
> In **System Preferences** > **Privacy & Security** > **App Management**, click "+" button, add "PDPatcher.app".
> Then try it again? Also don't forget to give it "Full Disk Access" :)

Thanks for the suggestion, but I just tried it and the problem wasn't solved.

**Comment by MikeWang000000** [comment]
> Thanks for the suggestion, but I just tried it and the problem wasn't solved.

The main script is at “Show Package Contents”，`Contents/Resources/script.sh`
You can run it manually via typing `sudo bash script.sh` in **Terminal.app** and see what happens on error.

**Comment by cernard** [comment]
> > Thanks for the suggestion, but I just tried it and the problem wasn't solved.
> 
> The main script is at “Show Package Contents”，`Contents/Resources/script.sh` You can run it manually via typing `sudo bash script.sh` in **Terminal.app** and see what happens on error.

Very thanks for your solution, I solved this issue. For me, I add PDPatcher to App Management first, then open Parallels Desktop, finally, open PDPatcher, input password, then works fine!

**Comment by seantech2000** [comment]
> sudo bash script.sh

`
Login failed: Unable to connect to Parallels Service. Make sure that the prl_disp_service process is active and it is not blocked by Firewall. For details, please refer to this knowledgebase article (https://www.parallels.com/products/desktop/supportinfo/pdfm18_C_249).
No matching processes were found
cp: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service.bak: Operation not permitted
chmod: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service.bak: No such file or directory
dd: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service: Operation not permitted
dd: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service: Operation not permitted
dd: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service: Operation not permitted
dd: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service: Operation not permitted
Error: Content mismatch

`

**Comment by seantech2000** [comment]
启动Parallels 后再打开PD，错误如下：
`
18097
The user has signed out successfully.
cp: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service.bak: Operation not permitted
chmod: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service.bak: No such file or directory
dd: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service: Operation not permitted
dd: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service: Operation not permitted
dd: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service: Operation not permitted
dd: /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service: Operation not permitted
Error: Content mismatch
`

**Comment by WarsFeng** [comment]
> > Thanks for the suggestion, but I just tried it and the problem wasn't solved.
> 
> The main script is at “Show Package Contents”，`Contents/Resources/script.sh` You can run it manually via typing `sudo bash script.sh` in **Terminal.app** and see what happens on error.

I add **Terminal.app** to App Management first, and run the `script.sh` successfully, Thanks.

**Comment by Jimmy-PM** [comment]
> > Thanks for the suggestion, but I just tried it and the problem wasn't solved.
> 
> The main script is at “Show Package Contents”，`Contents/Resources/script.sh` You can run it manually via typing `sudo bash script.sh` in **Terminal.app** and see what happens on error.

终端运行后显示查找不到相关路径（终端已授权访问所有磁盘文件）
设备：MacBook Pro（M1）
macOS版本：Ventura 13.0, 以及 PD版本是18.0.2
系统语言是中文
<img width="610" alt="image" src="https://user-images.githubusercontent.com/85380042/195977310-9a26ae76-e809-49ca-864a-976b93f1f4f1.png">

**Comment by MikeWang000000** [comment]
> 终端运行后显示查找不到相关路径（终端已授权访问所有磁盘文件） 设备：MacBook Pro（M1） macOS版本：Ventura 13.0, 以及 PD版本是18.0.2 系统语言是中文

输入`sudo bash`空格，然后将`script.sh`文件拖进命令行窗口，然后回车。这个文件在“显示包内容” -> Contents -> Resources 文件夹下。
输入你的密码（屏幕上什么都不会显示），回车，即执行。

**Comment by Jimmy-PM** [comment]
> > 终端运行后显示查找不到相关路径（终端已授权访问所有磁盘文件） 设备：MacBook Pro（M1） macOS版本：Ventura 13.0, 以及 PD版本是18.0.2 系统语言是中文
> 
> 输入`sudo bash`空格，然后将`script.sh`文件拖进命令行窗口，然后回车。这个文件在“显示包内容” -> Contents -> Resources 文件夹下。 输入你的密码（屏幕上什么都不会显示），回车，即执行。

问题已解决，非常感谢🙏

**Comment by detesion** [comment]
> > 终端运行后显示查找不到相关路径（终端已授权访问所有磁盘文件） 设备：MacBook Pro（M1） macOS版本：Ventura 13.0, 以及 PD版本是18.0.2 系统语言是中文
> 
> 输入`sudo bash`空格，然后将`script.sh`文件拖进命令行窗口，然后回车。这个文件在“显示包内容” -> Contents -> Resources 文件夹下。 输入你的密码（屏幕上什么都不会显示），回车，即执行。

额 默默的问一下显示包内容在哪里？

**Comment by detesion** [comment]
> > 终端运行后显示查找不到相关路径（终端已授权访问所有磁盘文件） 设备：MacBook Pro（M1） macOS版本：Ventura 13.0, 以及 PD版本是18.0.2 系统语言是中文
> 
> 输入`sudo bash`空格，然后将`script.sh`文件拖进命令行窗口，然后回车。这个文件在“显示包内容” -> Contents -> Resources 文件夹下。 输入你的密码（屏幕上什么都不会显示），回车，即执行。

我悟了，非常感谢你提供的解决方案！！！

**Comment by nonplaybox** [comment]
> sudo bash

Thanks, the problem has been solved.

**Comment by tarasis** [comment]
There was an error in `prl_disp_service` after about an hour of running . It seg faulted, complaining that it couldn't talk to service and killed both parallels and running windows. 

"Unable to connect to Parallels Service."
"Make sure that the prl_disp_service process is active and it is not blocked by Firewall. For details, please refer to <a href="https://www.parallels.com/products/desktop/supportinfo/pdfm18_en_US_249">this knowledgebase article</a>"

Give this patches said file, is this just an expected issue?

**Comment by SunOddman** [comment]
![image](https://user-images.githubusercontent.com/11980623/197787053-e69052cf-27bc-4667-b369-e788882b6399.png)
我的报这个

**Comment by MikeWang000000** [comment]
现在为了解决兼容性问题，将 app 更改为了 pkg 安装器，应该能通用于各个操作系统了。
我将关闭这个 issue ，如果问题仍存在，我会重新打开它。

To solve the compatibility problem, the app has now been changed to a pkg installer, which should be compatible with all macOS.
I'm going to close this issue and will reopen it if the problem still persists.
