### ISSUE TITLE
出现了这个 我下的它自带的win11镜像

### ISSUE THREAD

**Issue by ranyong1997** [MikeWang000000/PD-Runner-Revived#23]
<img width="908" alt="image" src="https://user-images.githubusercontent.com/67427627/197310338-c1daddb9-5a14-40cf-b8f8-d4146e76d154.png">

**Comment by MikeWang000000** [comment]
虽然但是，这和补丁没有关系

**Comment by ranyong1997** [comment]
我重装了PD18解决了
