### ISSUE TITLE
MacBook频繁卡顿

### ISSUE THREAD

**Issue by tangzichengcc** [MikeWang000000/PD-Runner-Revived#27]
MacBook pro2021 m1 pro芯片,macos13, pd runner 18.1.0 系统中文

就是电脑运行一段时间后,就会突然cpu飙升100% 把所有应用关掉也没用,只有重启才能解决,在安装pd runner之前没有遇到这个问题,

还有就是想请问,怎么卸载pdrunner

**Comment by MikeWang000000** [comment]
如果使用 18.1.0 ，您可能正在使用 PD Patcher ，而非 PD Runner 。PD Patcher 补丁包与 PD 结合，想要解除该补丁需要重新安装 PD（并不会影响到 PD 内部的虚拟机）。

卸载旧版 PD Runner（版本号为 v0.3.8 或更早）：
```bash
sudo launchctl disable system/com.lihaoyun6.PD-Runner-Helper
sudo rm /Library/LaunchDaemons/com.lihaoyun6.PD-Runner-Helper.plist
sudo rm /Library/PrivilegedHelperTools/com.lihaoyun6.PD-Runner-Helper
sudo rm ~/Library/Preferences/com.lihaoyun6.PD-Runner.plist
```

另外，请在活动监视器中查看具体占用 CPU 的程序是什么？

**Comment by tangzichengcc** [comment]
(其实我不知道是否和pd patcher有关,只是一种猜测,因为安装完后接着出的问题) (没有不好的意思哈)
是想诶个排除可能, 具体占用cpu的程序的话,systemstats,还有几个没看到,因为太卡啦,总之就是,不动就还好,cpu占用率百分之10左右,一动鼠标,一点击什么东西,就突然爆掉了,
<img width="632" alt="image" src="https://user-images.githubusercontent.com/43260130/200157469-d8a4626a-0815-4a46-b2b4-e3403c0e4e55.png">

问错问题啦,想问一下怎么卸载掉pd patcher,在安装的时候好像有看到有往系统服务里写什么东西?

**Comment by MikeWang000000** [comment]
Patcher 的话是没有向系统服务写东西的哦～

源码如你所见，没有写入任何服务：[[scripts/postinstall]](https://github.com/MikeWang000000/PD-Runner-Revived/blob/pdp/PDPatcher.tpl/scripts/postinstall)

以前旧版 Runner（就是 PD 启动器）倒是有的，它会自动修正系统时间。不过 Patcher 使用了完全不同的技术，它只是个补丁，不是独立的程序。

如果说是这个补丁让 PD 出 bug 了，造成 CPU 暴涨，也存在这种可能，不过还没有听到其他用户报告类似的情形。

总之，先排除下其他的情况？

**Comment by tangzichengcc** [comment]
好的谢谢！
