### ISSUE TITLE
Parallels Desktop 18.1.1

### ISSUE THREAD

**Issue by Drovosek01** [MikeWang000000/PD-Runner-Revived#28]
Installer:
https://download.parallels.com/desktop/v18/18.1.1-53328/ParallelsDesktop-18.1.1-53328.dmg

Release notes:
https://kb.parallels.com/129060

Need new patch...

**Comment by MikeWang000000** [comment]
Thanks for reminding, new patch will be available soon.

**Comment by kobehuanghai** [comment]
> Thanks for reminding, new patch will be available soon.

super efficient... cant thank you enough....

**Comment by MikeWang000000** [comment]
[PD Patcher v18.1.1](https://github.com/MikeWang000000/PD-Runner-Revived/releases/tag/18.1.1) now released

**Comment by Drovosek01** [comment]
> [PD Patcher v18.1.1](https://github.com/MikeWang000000/PD-Runner-Revived/releases/tag/18.1.1) now released

Thank you!
Tested on macOS Ventura Intel and it work.
