### ISSUE TITLE
PDPatcher_18.2.0-53488.pkg

### ISSUE THREAD

**Issue by BenjaminX** [MikeWang000000/PD-Runner-Revived#32]
prl_disp_service issues

**Comment by DowCore** [comment]
when is over

**Comment by MikeWang000000** [comment]
Sorry to say that PD has changed the verification mechanism since 18.2 so the previous patch method no longer works.
Please keep using old versions until a new patch method is discovered.

**Comment by moogerfoogers** [comment]
Damn. Well there's always hope it will work again after new patch.

**Comment by Drovosek01** [comment]
Just installer direct link:
https://download.parallels.com/desktop/v18/18.2.0-53488/ParallelsDesktop-18.2.0-53488.dmg

**Comment by BenjaminX** [comment]
[Archive.zip](https://github.com/MikeWang000000/PD-Runner-Revived/files/10775638/Archive.zip)

@MikeWang000000 pls check prl_disp_service offset values.

**Comment by MikeWang000000** [comment]
> [Archive.zip](https://github.com/MikeWang000000/PD-Runner-Revived/files/10775638/Archive.zip)
> 
> @MikeWang000000 pls check prl_disp_service offset values.

I know this patch. It's from *macat*.
Can you run virtual machines without error with this patch?
For me, it does not work at all :/
It's not enough to just modify the service binary since that change.

**Comment by DowCore** [comment]
大佬的研究进度怎么样了

**Comment by MikeWang000000** [comment]
> 大佬的研究进度怎么样了

现在无限期停更了。关于因为有签名验证，SIP启用的情况下是没法绕过保护的。
总之，18.1.1是最后一个稳定的完美静态patch，后面就算有也不会完美了。

**Comment by Greyisttot** [comment]
好难过，还好我没更新，要是PD强制更新久GG了

**Comment by MikeWang000000** [comment]
> 好难过，还好我没更新，要是PD强制更新久GG了

现在我们静观其变，18.1.1已经很稳定了，可以用好一段时间，等有问题再说。

不小心更新了也不要紧，断网装旧版，再启用网络依然能用。

也不用担心强制更新的事，第一，我们没有发现这种功能；第二，如果万一真的存在，前期版本都是可修改的，到时候我们也能另打补丁关掉。

**Comment by wooodswu** [comment]
> > 好难过，还好我没更新，要是PD强制更新久GG了
> 
> 现在我们静观其变，18.1.1已经很稳定了，可以用好一段时间，等有问题再说。
> 
> 不小心更新了也不要紧，断网装旧版，再启用网络依然能用。
> 
> 也不用担心强制更新的事，第一，我们没有发现这种功能；第二，如果万一真的存在，前期版本都是可修改的，到时候我们也能另打补丁关掉。

大佬 有没有旧版paralleldesktop 18.2之前的安装包，找了半天没找到。

**Comment by MikeWang000000** [comment]
> > > 好难过，还好我没更新，要是PD强制更新久GG了
> > 
> > 
> > 现在我们静观其变，18.1.1已经很稳定了，可以用好一段时间，等有问题再说。
> > 不小心更新了也不要紧，断网装旧版，再启用网络依然能用。
> > 也不用担心强制更新的事，第一，我们没有发现这种功能；第二，如果万一真的存在，前期版本都是可修改的，到时候我们也能另打补丁关掉。
> 
> 大佬 有没有旧版paralleldesktop 18.2之前的安装包，找了半天没找到。

直接运行对应旧版PDPatcher就好。它会自动引导你下载。

**Comment by ppttvs** [comment]
> > > 好难过，还好我没更新，要是PD强制更新久GG了
> > 
> > 
> > 现在我们静观其变，18.1.1已经很稳定了，可以用好一段时间，等有问题再说。
> > 不小心更新了也不要紧，断网装旧版，再启用网络依然能用。
> > 也不用担心强制更新的事，第一，我们没有发现这种功能；第二，如果万一真的存在，前期版本都是可修改的，到时候我们也能另打补丁关掉。
> 
> 大佬 有没有旧版paralleldesktop 18.2之前的安装包，找了半天没找到。

https://download.parallels.com/desktop/v18/18.1.1-53328/ParallelsDesktop-18.1.1-53328.dmg

Just in case

**Comment by jimmyyukio** [comment]
Thank you .The old version installation package is really helpful.

**Comment by jimmyyukio** [comment]
> > > > 好难过，还好我没更新，要是 PD 强制更新久 GG 了
> > > 
> > > 
> > > 现在我们静观其变，18.1.1 已经很稳定了，可以用好一段时间，等有问题再说。
> > > 不小心更新了也不要紧，断网装旧版，再启用网络依然能用。
> > > 也不用担心强制更新的事，第一，我们没有发现这种功能；第二，如果万一真的存在，前期版本都是可修改的，到时候我们也能另打补丁关掉。
> > 
> > 
> > 大佬 有没有旧版 paralleldesktop 18.2 之前的安装包，找了半天没找到。
> 
> https://download.parallels.com/desktop/v18/18.1.1-53328/ParallelsDesktop-18.1.1-53328.dmg
> 
> Just in case

Thank you .The old version installation package is really helpful.

**Comment by dzzhyk** [comment]
> > > > 好难过，还好我没更新，要是PD强制更新久GG了
> > > 
> > > 
> > > 现在我们静观其变，18.1.1已经很稳定了，可以用好一段时间，等有问题再说。
> > > 不小心更新了也不要紧，断网装旧版，再启用网络依然能用。
> > > 也不用担心强制更新的事，第一，我们没有发现这种功能；第二，如果万一真的存在，前期版本都是可修改的，到时候我们也能另打补丁关掉。
> > 
> > 
> > 大佬 有没有旧版paralleldesktop 18.2之前的安装包，找了半天没找到。
> 
> https://download.parallels.com/desktop/v18/18.1.1-53328/ParallelsDesktop-18.1.1-53328.dmg
> 
> Just in case

这个链接ok的，注意，如果安装后弹出要求更新到18.2.0，直接左上角关掉后，选择“不，使用当前版本”

**Comment by Linbox666** [comment]
如果关闭SIP的情况下，是否可行呢，可能部分人需要最新版本

**Comment by wooodswu** [comment]
> > 大佬的研究进度怎么样了
> 
> 现在无限期停更了。关于因为有签名验证，SIP启用的情况下是没法绕过保护的。 总之，18.1.1是最后一个稳定的完美静态patch，后面就算有也不会完美了。

大佬，请问这个这样安装成功没
<img width="607" alt="image" src="https://github.com/MikeWang000000/PD-Runner-Revived/assets/87766834/c4815a5d-28ac-4d5c-a922-1915757778e8">

<img width="617" alt="image" src="https://github.com/MikeWang000000/PD-Runner-Revived/assets/87766834/2d46e593-de65-4040-bd71-3aabdab01e58">

**Comment by BenjaminX** [comment]
不用纠结了，已经不能用了。要不忍住老版继续用，要不付费。
