### ISSUE TITLE
technical preview one 16.3.2

### ISSUE THREAD

**Issue by albertputinjobs** [MikeWang000000/PD-Runner-Revived#33]
I uploaded that one on my google drive https://drive.google.com/file/d/1fUs18KeeHPRRFm294MTvaeAK2-XunAlp/view?usp=drivesdk

**Comment by MikeWang000000** [comment]
8697cd44bf25c01487f73a15fa8ef638d35d8553 [PDPatcher_16.3.2-50531.zip](https://github.com/MikeWang000000/PD-Runner-Revived/files/10746486/PDPatcher_16.3.2-50531.zip)

**Comment by albertputinjobs** [comment]
above patch is not working it is still showing license page
