### ISSUE TITLE
系统更新到 12.4 不能启动了

### ISSUE THREAD

**Issue by Zjinxing** [MikeWang000000/PD-Runner-Revived#7]
提示启动失败 Failed to start the VM: Operation canceled. The operation has been canceled.

**Comment by yaoliu** [comment]
我这边把时间改到过去 用PD软件把虚拟机重启一遍 提示reset 点击完都能启动成功 然后再把时间改回来 在使用runner启动就好了

**Comment by lifenglsf** [comment]
我的0.3.6不能用，网上找到了0.3.7，刚启动也是failed to start提示，但是虚拟机还是启动了的。退出再打开，开启虚拟机没有报错过，还是可以正常用的

**Comment by Zjinxing** [comment]
我最后把虚拟机删除重新安装解决的
